site_name: opendota-async
docs_dir: docs
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../src]
nav:
  - Home: index.md
  - Publishing to PyPI: publishing.md
